// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
)

const deleteSession = `-- name: DeleteSession :execrows
DELETE FROM sessions WHERE token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash []byte) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSession, tokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
