// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const listRoles = `-- name: ListRoles :many
SELECT r.id, r.name,
    COALESCE(array_agg(rp.permission ORDER BY rp.permission) FILTER (WHERE rp.permission IS NOT NULL), '{}')::text[] AS permissions,
    (SELECT count(*) FROM user_roles ur WHERE ur.role_id = r.id)::int AS user_count
FROM roles r
LEFT JOIN role_permissions rp ON rp.role_id = r.id
GROUP BY r.id
ORDER BY lower(r.name), r.name
`

type ListRolesRow struct {
	ID          uuid.UUID
	Name        string
	Permissions []string
	UserCount   int32
}

func (q *Queries) ListRoles(ctx context.Context) ([]ListRolesRow, error) {
	rows, err := q.db.Query(ctx, listRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRolesRow
	for rows.Next() {
		var i ListRolesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Permissions,
			&i.UserCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
