// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const insertPermissions = `-- name: InsertPermissions :exec
INSERT INTO role_permissions (role_id, permission) SELECT $1::uuid, unnest($2::text[])
`

type InsertPermissionsParams struct {
	RoleID      uuid.UUID
	Permissions []string
}

func (q *Queries) InsertPermissions(ctx context.Context, arg InsertPermissionsParams) error {
	_, err := q.db.Exec(ctx, insertPermissions, arg.RoleID, arg.Permissions)
	return err
}

const insertRole = `-- name: InsertRole :one
INSERT INTO roles (name) VALUES ($1) RETURNING id, name
`

func (q *Queries) InsertRole(ctx context.Context, name string) (Role, error) {
	row := q.db.QueryRow(ctx, insertRole, name)
	var i Role
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
