// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const insertUser = `-- name: InsertUser :one
INSERT INTO users (email, name, password_hash) VALUES ($1, $2, $3)
ON CONFLICT (email) DO NOTHING
RETURNING id, email, name, created_at
`

type InsertUserParams struct {
	Email        string
	Name         string
	PasswordHash string
}

type InsertUserRow struct {
	ID        uuid.UUID
	Email     string
	Name      string
	CreatedAt time.Time
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (InsertUserRow, error) {
	row := q.db.QueryRow(ctx, insertUser, arg.Email, arg.Name, arg.PasswordHash)
	var i InsertUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}
