// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const clearUserRoles = `-- name: ClearUserRoles :exec
DELETE FROM user_roles WHERE user_id = $1
`

func (q *Queries) ClearUserRoles(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearUserRoles, userID)
	return err
}

const countOtherActiveHolders = `-- name: CountOtherActiveHolders :one
SELECT count(*)::int FROM user_roles ur JOIN users u ON u.id = ur.user_id
WHERE ur.role_id = $1 AND u.deactivated_at IS NULL AND u.id <> $2
`

type CountOtherActiveHoldersParams struct {
	RoleID uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) CountOtherActiveHolders(ctx context.Context, arg CountOtherActiveHoldersParams) (int32, error) {
	row := q.db.QueryRow(ctx, countOtherActiveHolders, arg.RoleID, arg.UserID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteUserSessions = `-- name: DeleteUserSessions :execrows
DELETE FROM sessions WHERE user_id = $1
`

func (q *Queries) DeleteUserSessions(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUserSessions, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertUserRoles = `-- name: InsertUserRoles :exec
INSERT INTO user_roles (user_id, role_id) SELECT $1::uuid, unnest($2::uuid[])
`

type InsertUserRolesParams struct {
	UserID  uuid.UUID
	RoleIds []uuid.UUID
}

func (q *Queries) InsertUserRoles(ctx context.Context, arg InsertUserRolesParams) error {
	_, err := q.db.Exec(ctx, insertUserRoles, arg.UserID, arg.RoleIds)
	return err
}

const lockAdminRole = `-- name: LockAdminRole :one
SELECT id FROM roles WHERE name = 'admin' FOR UPDATE
`

func (q *Queries) LockAdminRole(ctx context.Context) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockAdminRole)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const lockUser = `-- name: LockUser :one
SELECT id FROM users WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockUser(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockUser, id)
	var id_2 uuid.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const rolesByID = `-- name: RolesByID :many
SELECT id, name FROM roles WHERE id = ANY($1::uuid[])
`

func (q *Queries) RolesByID(ctx context.Context, ids []uuid.UUID) ([]Role, error) {
	rows, err := q.db.Query(ctx, rolesByID, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userRoles = `-- name: UserRoles :many
SELECT r.id, r.name FROM user_roles ur JOIN roles r ON r.id = ur.role_id WHERE ur.user_id = $1
`

func (q *Queries) UserRoles(ctx context.Context, userID uuid.UUID) ([]Role, error) {
	rows, err := q.db.Query(ctx, userRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
