// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const deleteOtherSessions = `-- name: DeleteOtherSessions :execrows
DELETE FROM sessions WHERE user_id = $1 AND token_hash <> $2
`

type DeleteOtherSessionsParams struct {
	UserID    uuid.UUID
	TokenHash []byte
}

func (q *Queries) DeleteOtherSessions(ctx context.Context, arg DeleteOtherSessionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOtherSessions, arg.UserID, arg.TokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const passwordHash = `-- name: PasswordHash :one
SELECT password_hash FROM users WHERE id = $1
`

func (q *Queries) PasswordHash(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, passwordHash, id)
	var password_hash string
	err := row.Scan(&password_hash)
	return password_hash, err
}

const updatePasswordHash = `-- name: UpdatePasswordHash :exec
UPDATE users SET password_hash = $2 WHERE id = $1
`

type UpdatePasswordHashParams struct {
	ID           uuid.UUID
	PasswordHash string
}

func (q *Queries) UpdatePasswordHash(ctx context.Context, arg UpdatePasswordHashParams) error {
	_, err := q.db.Exec(ctx, updatePasswordHash, arg.ID, arg.PasswordHash)
	return err
}
