// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countHolders = `-- name: CountHolders :one
SELECT count(*)::int FROM user_roles WHERE role_id = $1
`

func (q *Queries) CountHolders(ctx context.Context, roleID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countHolders, roleID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const deletePermissions = `-- name: DeletePermissions :exec
DELETE FROM role_permissions WHERE role_id = $1
`

func (q *Queries) DeletePermissions(ctx context.Context, roleID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePermissions, roleID)
	return err
}

const insertPermissions = `-- name: InsertPermissions :exec
INSERT INTO role_permissions (role_id, permission) SELECT $1::uuid, unnest($2::text[])
`

type InsertPermissionsParams struct {
	RoleID      uuid.UUID
	Permissions []string
}

func (q *Queries) InsertPermissions(ctx context.Context, arg InsertPermissionsParams) error {
	_, err := q.db.Exec(ctx, insertPermissions, arg.RoleID, arg.Permissions)
	return err
}

const lockRole = `-- name: LockRole :one
SELECT id, name FROM roles WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockRole(ctx context.Context, id uuid.UUID) (Role, error) {
	row := q.db.QueryRow(ctx, lockRole, id)
	var i Role
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const renameRole = `-- name: RenameRole :exec
UPDATE roles SET name = $2 WHERE id = $1
`

type RenameRoleParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) RenameRole(ctx context.Context, arg RenameRoleParams) error {
	_, err := q.db.Exec(ctx, renameRole, arg.ID, arg.Name)
	return err
}

const rolePermissions = `-- name: RolePermissions :many
SELECT permission FROM role_permissions WHERE role_id = $1 ORDER BY permission
`

func (q *Queries) RolePermissions(ctx context.Context, roleID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, rolePermissions, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var permission string
		if err := rows.Scan(&permission); err != nil {
			return nil, err
		}
		items = append(items, permission)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
