// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const userByID = `-- name: UserByID :one
SELECT id, email, name, created_at, deactivated_at FROM users WHERE id = $1
`

type UserByIDRow struct {
	ID            uuid.UUID
	Email         string
	Name          string
	CreatedAt     time.Time
	DeactivatedAt *time.Time
}

func (q *Queries) UserByID(ctx context.Context, id uuid.UUID) (UserByIDRow, error) {
	row := q.db.QueryRow(ctx, userByID, id)
	var i UserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
		&i.DeactivatedAt,
	)
	return i, err
}
