// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const lockUser = `-- name: LockUser :one
SELECT id, email, name, created_at, deactivated_at FROM users WHERE id = $1 FOR UPDATE
`

type LockUserRow struct {
	ID            uuid.UUID
	Email         string
	Name          string
	CreatedAt     time.Time
	DeactivatedAt *time.Time
}

func (q *Queries) LockUser(ctx context.Context, id uuid.UUID) (LockUserRow, error) {
	row := q.db.QueryRow(ctx, lockUser, id)
	var i LockUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
		&i.DeactivatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET email = $2, name = $3 WHERE id = $1
RETURNING id, email, name, created_at, deactivated_at
`

type UpdateUserParams struct {
	ID    uuid.UUID
	Email string
	Name  string
}

type UpdateUserRow struct {
	ID            uuid.UUID
	Email         string
	Name          string
	CreatedAt     time.Time
	DeactivatedAt *time.Time
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.ID, arg.Email, arg.Name)
	var i UpdateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
		&i.DeactivatedAt,
	)
	return i, err
}
