// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditEvent struct {
	ID           int64
	OccurredAt   time.Time
	ActorID      pgtype.UUID
	Action       string
	ResourceType string
	ResourceID   string
	Before       []byte
	After        []byte
	Ip           *netip.Addr
	RequestID    string
}

type LoginAttempt struct {
	Kind string
	Key  string
	At   time.Time
}

type Role struct {
	ID   uuid.UUID
	Name string
}

type RolePermission struct {
	RoleID     uuid.UUID
	Permission string
}

type Session struct {
	TokenHash []byte
	UserID    uuid.UUID
	CreatedAt time.Time
}

type User struct {
	ID            uuid.UUID
	Email         string
	Name          string
	PasswordHash  string
	CreatedAt     time.Time
	DeactivatedAt *time.Time
}

type UserRole struct {
	UserID uuid.UUID
	RoleID uuid.UUID
}
