// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const listEvents = `-- name: ListEvents :many
SELECT e.id, e.occurred_at, e.action, e.actor_id, u.email AS actor_email,
    e.resource_type, e.resource_id, COALESCE(host(e.ip), '')::text AS ip, e.request_id
FROM audit_events e
LEFT JOIN users u ON u.id = e.actor_id
WHERE ($1::bigint IS NULL OR e.id < $1::bigint)
  AND ($2::text IS NULL OR e.action = $2::text)
  AND ($3::uuid IS NULL OR e.actor_id = $3::uuid)
  AND ($4::text IS NULL OR e.resource_type = $4::text)
  AND ($5::text IS NULL OR e.resource_id = $5::text)
  AND ($6::timestamptz IS NULL OR e.occurred_at >= $6::timestamptz)
  AND ($7::timestamptz IS NULL OR e.occurred_at < $7::timestamptz)
ORDER BY e.id DESC
LIMIT $8::int
`

type ListEventsParams struct {
	Before       pgtype.Int8
	Action       pgtype.Text
	ActorID      pgtype.UUID
	ResourceType pgtype.Text
	ResourceID   pgtype.Text
	FromAt       *time.Time
	ToAt         *time.Time
	RowLimit     int32
}

type ListEventsRow struct {
	ID           int64
	OccurredAt   time.Time
	Action       string
	ActorID      pgtype.UUID
	ActorEmail   pgtype.Text
	ResourceType string
	ResourceID   string
	Ip           string
	RequestID    string
}

func (q *Queries) ListEvents(ctx context.Context, arg ListEventsParams) ([]ListEventsRow, error) {
	rows, err := q.db.Query(ctx, listEvents,
		arg.Before,
		arg.Action,
		arg.ActorID,
		arg.ResourceType,
		arg.ResourceID,
		arg.FromAt,
		arg.ToAt,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEventsRow
	for rows.Next() {
		var i ListEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.OccurredAt,
			&i.Action,
			&i.ActorID,
			&i.ActorEmail,
			&i.ResourceType,
			&i.ResourceID,
			&i.Ip,
			&i.RequestID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
