// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const activate = `-- name: Activate :exec
UPDATE users SET deactivated_at = NULL WHERE id = $1
`

func (q *Queries) Activate(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, activate, id)
	return err
}

const lockUser = `-- name: LockUser :one
SELECT id, email, name, deactivated_at FROM users WHERE id = $1 FOR UPDATE
`

type LockUserRow struct {
	ID            uuid.UUID
	Email         string
	Name          string
	DeactivatedAt *time.Time
}

func (q *Queries) LockUser(ctx context.Context, id uuid.UUID) (LockUserRow, error) {
	row := q.db.QueryRow(ctx, lockUser, id)
	var i LockUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.DeactivatedAt,
	)
	return i, err
}
