// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const getEvent = `-- name: GetEvent :one
SELECT e.id, e.occurred_at, e.action, e.actor_id, u.email AS actor_email,
    e.resource_type, e.resource_id, COALESCE(host(e.ip), '')::text AS ip, e.request_id, e.before, e.after
FROM audit_events e
LEFT JOIN users u ON u.id = e.actor_id
WHERE e.id = $1
`

type GetEventRow struct {
	ID           int64
	OccurredAt   time.Time
	Action       string
	ActorID      pgtype.UUID
	ActorEmail   pgtype.Text
	ResourceType string
	ResourceID   string
	Ip           string
	RequestID    string
	Before       []byte
	After        []byte
}

func (q *Queries) GetEvent(ctx context.Context, id int64) (GetEventRow, error) {
	row := q.db.QueryRow(ctx, getEvent, id)
	var i GetEventRow
	err := row.Scan(
		&i.ID,
		&i.OccurredAt,
		&i.Action,
		&i.ActorID,
		&i.ActorEmail,
		&i.ResourceType,
		&i.ResourceID,
		&i.Ip,
		&i.RequestID,
		&i.Before,
		&i.After,
	)
	return i, err
}
