// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deactivate = `-- name: Deactivate :one
UPDATE users SET deactivated_at = now() WHERE id = $1 RETURNING deactivated_at
`

func (q *Queries) Deactivate(ctx context.Context, id uuid.UUID) (*time.Time, error) {
	row := q.db.QueryRow(ctx, deactivate, id)
	var deactivated_at *time.Time
	err := row.Scan(&deactivated_at)
	return deactivated_at, err
}

const deleteUserSessions = `-- name: DeleteUserSessions :execrows
DELETE FROM sessions WHERE user_id = $1
`

func (q *Queries) DeleteUserSessions(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUserSessions, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const lockUser = `-- name: LockUser :one
SELECT id, email, name, deactivated_at FROM users WHERE id = $1 FOR UPDATE
`

type LockUserRow struct {
	ID            uuid.UUID
	Email         string
	Name          string
	DeactivatedAt *time.Time
}

func (q *Queries) LockUser(ctx context.Context, id uuid.UUID) (LockUserRow, error) {
	row := q.db.QueryRow(ctx, lockUser, id)
	var i LockUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.DeactivatedAt,
	)
	return i, err
}
