// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const clearEmailAttempts = `-- name: ClearEmailAttempts :exec
DELETE FROM login_attempts WHERE kind = 'email' AND key = $1
`

func (q *Queries) ClearEmailAttempts(ctx context.Context, key string) error {
	_, err := q.db.Exec(ctx, clearEmailAttempts, key)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const pruneAttempts = `-- name: PruneAttempts :exec
DELETE FROM login_attempts WHERE at <= now() - interval '15 minutes'
`

func (q *Queries) PruneAttempts(ctx context.Context) error {
	_, err := q.db.Exec(ctx, pruneAttempts)
	return err
}

const recordAttempt = `-- name: RecordAttempt :exec
INSERT INTO login_attempts (kind, key) VALUES ($1, $2)
`

type RecordAttemptParams struct {
	Kind string
	Key  string
}

func (q *Queries) RecordAttempt(ctx context.Context, arg RecordAttemptParams) error {
	_, err := q.db.Exec(ctx, recordAttempt, arg.Kind, arg.Key)
	return err
}

const retryAfter = `-- name: RetryAfter :one
SELECT ceil(extract(epoch FROM (at + interval '15 minutes' - now())))::int AS seconds
FROM login_attempts
WHERE kind = $1 AND key = $2 AND at > now() - interval '15 minutes'
ORDER BY at DESC
OFFSET $3::int
LIMIT 1
`

type RetryAfterParams struct {
	Kind          string
	Key           string
	LimitMinusOne int32
}

func (q *Queries) RetryAfter(ctx context.Context, arg RetryAfterParams) (int32, error) {
	row := q.db.QueryRow(ctx, retryAfter, arg.Kind, arg.Key, arg.LimitMinusOne)
	var seconds int32
	err := row.Scan(&seconds)
	return seconds, err
}

const updatePasswordHash = `-- name: UpdatePasswordHash :exec
UPDATE users SET password_hash = $2 WHERE id = $1
`

type UpdatePasswordHashParams struct {
	ID           uuid.UUID
	PasswordHash string
}

func (q *Queries) UpdatePasswordHash(ctx context.Context, arg UpdatePasswordHashParams) error {
	_, err := q.db.Exec(ctx, updatePasswordHash, arg.ID, arg.PasswordHash)
	return err
}

const userByEmail = `-- name: UserByEmail :one
SELECT id, password_hash, deactivated_at FROM users WHERE email = $1
`

type UserByEmailRow struct {
	ID            uuid.UUID
	PasswordHash  string
	DeactivatedAt *time.Time
}

func (q *Queries) UserByEmail(ctx context.Context, email string) (UserByEmailRow, error) {
	row := q.db.QueryRow(ctx, userByEmail, email)
	var i UserByEmailRow
	err := row.Scan(&i.ID, &i.PasswordHash, &i.DeactivatedAt)
	return i, err
}
