/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedAccountPasswordRouteImport } from './routes/_authed/account/password'
import { Route as AuthedAuditIndexRouteImport } from './routes/_authed/audit/index'
import { Route as AuthedAuditIdRouteImport } from './routes/_authed/audit/$id'
import { Route as AuthedRolesIndexRouteImport } from './routes/_authed/roles/index'
import { Route as AuthedRolesIdRouteImport } from './routes/_authed/roles/$id'
import { Route as AuthedRolesNewRouteImport } from './routes/_authed/roles/new'
import { Route as AuthedUsersIndexRouteImport } from './routes/_authed/users/index'
import { Route as AuthedUsersIdRouteImport } from './routes/_authed/users/$id'
import { Route as AuthedUsersNewRouteImport } from './routes/_authed/users/new'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAccountPasswordRoute = AuthedAccountPasswordRouteImport.update({
  id: '/account/password',
  path: '/account/password',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAuditIndexRoute = AuthedAuditIndexRouteImport.update({
  id: '/audit/',
  path: '/audit/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAuditIdRoute = AuthedAuditIdRouteImport.update({
  id: '/audit/$id',
  path: '/audit/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRolesIndexRoute = AuthedRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRolesIdRoute = AuthedRolesIdRouteImport.update({
  id: '/roles/$id',
  path: '/roles/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRolesNewRoute = AuthedRolesNewRouteImport.update({
  id: '/roles/new',
  path: '/roles/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedUsersIndexRoute = AuthedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedUsersIdRoute = AuthedUsersIdRouteImport.update({
  id: '/users/$id',
  path: '/users/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedUsersNewRoute = AuthedUsersNewRouteImport.update({
  id: '/users/new',
  path: '/users/new',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/account/password': typeof AuthedAccountPasswordRoute
  '/audit/$id': typeof AuthedAuditIdRoute
  '/roles/$id': typeof AuthedRolesIdRoute
  '/roles/new': typeof AuthedRolesNewRoute
  '/users/$id': typeof AuthedUsersIdRoute
  '/users/new': typeof AuthedUsersNewRoute
  '/audit/': typeof AuthedAuditIndexRoute
  '/roles/': typeof AuthedRolesIndexRoute
  '/users/': typeof AuthedUsersIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AuthedIndexRoute
  '/account/password': typeof AuthedAccountPasswordRoute
  '/audit/$id': typeof AuthedAuditIdRoute
  '/roles/$id': typeof AuthedRolesIdRoute
  '/roles/new': typeof AuthedRolesNewRoute
  '/users/$id': typeof AuthedUsersIdRoute
  '/users/new': typeof AuthedUsersNewRoute
  '/audit': typeof AuthedAuditIndexRoute
  '/roles': typeof AuthedRolesIndexRoute
  '/users': typeof AuthedUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/account/password': typeof AuthedAccountPasswordRoute
  '/_authed/audit/$id': typeof AuthedAuditIdRoute
  '/_authed/roles/$id': typeof AuthedRolesIdRoute
  '/_authed/roles/new': typeof AuthedRolesNewRoute
  '/_authed/users/$id': typeof AuthedUsersIdRoute
  '/_authed/users/new': typeof AuthedUsersNewRoute
  '/_authed/audit/': typeof AuthedAuditIndexRoute
  '/_authed/roles/': typeof AuthedRolesIndexRoute
  '/_authed/users/': typeof AuthedUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/account/password'
    | '/audit/$id'
    | '/roles/$id'
    | '/roles/new'
    | '/users/$id'
    | '/users/new'
    | '/audit/'
    | '/roles/'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/account/password'
    | '/audit/$id'
    | '/roles/$id'
    | '/roles/new'
    | '/users/$id'
    | '/users/new'
    | '/audit'
    | '/roles'
    | '/users'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/_authed/'
    | '/_authed/account/password'
    | '/_authed/audit/$id'
    | '/_authed/roles/$id'
    | '/_authed/roles/new'
    | '/_authed/users/$id'
    | '/_authed/users/new'
    | '/_authed/audit/'
    | '/_authed/roles/'
    | '/_authed/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/account/password': {
      id: '/_authed/account/password'
      path: '/account/password'
      fullPath: '/account/password'
      preLoaderRoute: typeof AuthedAccountPasswordRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/audit/': {
      id: '/_authed/audit/'
      path: '/audit'
      fullPath: '/audit/'
      preLoaderRoute: typeof AuthedAuditIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/audit/$id': {
      id: '/_authed/audit/$id'
      path: '/audit/$id'
      fullPath: '/audit/$id'
      preLoaderRoute: typeof AuthedAuditIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/roles/': {
      id: '/_authed/roles/'
      path: '/roles'
      fullPath: '/roles/'
      preLoaderRoute: typeof AuthedRolesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/roles/$id': {
      id: '/_authed/roles/$id'
      path: '/roles/$id'
      fullPath: '/roles/$id'
      preLoaderRoute: typeof AuthedRolesIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/roles/new': {
      id: '/_authed/roles/new'
      path: '/roles/new'
      fullPath: '/roles/new'
      preLoaderRoute: typeof AuthedRolesNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/users/': {
      id: '/_authed/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthedUsersIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/users/$id': {
      id: '/_authed/users/$id'
      path: '/users/$id'
      fullPath: '/users/$id'
      preLoaderRoute: typeof AuthedUsersIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/users/new': {
      id: '/_authed/users/new'
      path: '/users/new'
      fullPath: '/users/new'
      preLoaderRoute: typeof AuthedUsersNewRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedAccountPasswordRoute: typeof AuthedAccountPasswordRoute
  AuthedAuditIdRoute: typeof AuthedAuditIdRoute
  AuthedRolesIdRoute: typeof AuthedRolesIdRoute
  AuthedRolesNewRoute: typeof AuthedRolesNewRoute
  AuthedUsersIdRoute: typeof AuthedUsersIdRoute
  AuthedUsersNewRoute: typeof AuthedUsersNewRoute
  AuthedAuditIndexRoute: typeof AuthedAuditIndexRoute
  AuthedRolesIndexRoute: typeof AuthedRolesIndexRoute
  AuthedUsersIndexRoute: typeof AuthedUsersIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedAccountPasswordRoute: AuthedAccountPasswordRoute,
  AuthedAuditIdRoute: AuthedAuditIdRoute,
  AuthedRolesIdRoute: AuthedRolesIdRoute,
  AuthedRolesNewRoute: AuthedRolesNewRoute,
  AuthedUsersIdRoute: AuthedUsersIdRoute,
  AuthedUsersNewRoute: AuthedUsersNewRoute,
  AuthedAuditIndexRoute: AuthedAuditIndexRoute,
  AuthedRolesIndexRoute: AuthedRolesIndexRoute,
  AuthedUsersIndexRoute: AuthedUsersIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
