// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countHolders = `-- name: CountHolders :one
SELECT count(*)::int FROM user_roles WHERE role_id = $1
`

func (q *Queries) CountHolders(ctx context.Context, roleID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countHolders, roleID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteRole = `-- name: DeleteRole :exec
DELETE FROM roles WHERE id = $1
`

func (q *Queries) DeleteRole(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRole, id)
	return err
}

const lockRole = `-- name: LockRole :one
SELECT id, name FROM roles WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockRole(ctx context.Context, id uuid.UUID) (Role, error) {
	row := q.db.QueryRow(ctx, lockRole, id)
	var i Role
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const rolePermissions = `-- name: RolePermissions :many
SELECT permission FROM role_permissions WHERE role_id = $1 ORDER BY permission
`

func (q *Queries) RolePermissions(ctx context.Context, roleID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, rolePermissions, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var permission string
		if err := rows.Scan(&permission); err != nil {
			return nil, err
		}
		items = append(items, permission)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
